### ISSUE TITLE
YOLOv8 small model and 640 x 640 images

### ISSUE THREAD

**Issue by g2-bernotas** [rigvedrs/YOLO-V11-CAM#29]
A very useful repo - thanks! I have tested it with various sizes of YOLOv8 models and square images of different resolutions (64, 128, 256, 512, 640, 768, 1024 px). However, I encountered an issue when using the YOLOv8 small model with 640 x 640 images (as well as 768 px images). While the model trained and tested with 1024 px images showed slight improvement, it focused on very small areas (spots/patches) rather than the intended regions.

For 640 and  px images, the model highlights most of the image except for the areas it should be paying attention to. I attempted to invert the activations (1 - activations), but the results were unsatisfactory. I trained the model using three different datasets, but all yielded similar outputs.

I don't think this is EigenCAM related as it worked with differently sized images, but, also, the YOLO models worked well with differently sized images. Do you have any suggestions? Has anyone notice something similar?

Thank you in advance for your help.

**Comment by rigvedrs** [comment]
This has been fixed in the above mentioned PR. You can check it [here](https://github.com/rigvedrs/YOLO-V11-CAM/pull/34)

**Comment by g2-bernotas** [comment]
Great! Since I had problems with the small model, I checked a few that I had trained with different resolutions. I can confirm that the PR fixed the problems I had with the small model and resolution 320, 768, 1024, but I am still receiving the same results for resolution 640 x 640. Only the small model is affected.
